language: java
before_script:
- echo "Starting build"
script:
- mvn clean package
after_script:
- echo "Script finished"
after_success:
- echo "Build ready"
- ls -l $TRAVIS_BUILD_DIR/target
after_failure:
- echo "Build failure"
deploy:
- provider: heroku
api_key: 83585364-3052-4491-8be1-5ecad50bb1bb
